chore: upgrade to 1.13.0
r0gue-io/pop-node pull request #194
Opened 2024-08-15 10:15 UTC by chungquantin

2024-08-15 10:25 UTC, chungquantin commented on Cargo.toml
> -cumulus-pallet-parachain-system = { version = "0.13.0", default-features = false, features = [
https://github.com/paritytech/polkadot-sdk/pull/4380

2024-08-15 10:25 UTC, chungquantin commented on runtime/devnet/src/extensions.rs
> +	let base_weight: Weight = T::WeightInfo::seal_return(len);
https://github.com/paritytech/polkadot-sdk/pull/4233/files#:~:text=*self%20%7B-,match%20*self%20%7B,CopyFromContract(len)%20%3D%3E,-T%3A%3AWeightInfo

2024-08-15 10:25 UTC, chungquantin commented on runtime/devnet/src/extensions.rs
> +	let base_weight: Weight = T::WeightInfo::seal_return(env.in_len());
https://github.com/paritytech/polkadot-sdk/pull/4233/files#:~:text=*self%20%7B-,match%20*self%20%7B,CopyFromContract(len)%20%3D%3E,-T%3A%3AWeightInfo

2024-08-15 10:25 UTC, chungquantin commented on runtime/devnet/src/lib.rs
> +	// Limit the number of messages and signals a HRML channel can have at most
https://github.com/paritytech/polkadot-sdk/pull/3952

2024-08-15 10:25 UTC, chungquantin commented on runtime/testnet/Cargo.toml
> +
https://github.com/paritytech/polkadot-sdk/pull/4274

2024-08-15 19:24 UTC, peterwht approved these changes
Nicely done

2024-08-16 05:02 UTC, peterwht commented
[sc-1154]

2024-08-16 10:51 UTC, al3mart requested changes
The only nit would be if we can change the parameters of `enable_metadata_hash` in our `runtime/*/build.rs` to use `PAS` instead of `UNIT`.

2024-08-17 07:57 UTC, al3mart approved these changes

2024-08-17 07:58 UTC, merged