docs: release tracking issue template
r0gue-io/pop-node pull request #232
Opened 2024-08-23 15:01 UTC by al3mart

Based on the previous checklist we have used for 0.4.0 - https://github.com/r0gue-io/pop-node/issues/221
I have created this template that we can re-use for future releases of both, node and runtime, until we start moving to a move automated, CI self contained process.

2024-08-23 19:36 UTC, peterwht requested changes

2024-08-23 19:36 UTC, peterwht commented on .github/ISSUE_TEMPLATE/release_tracking.md
> +> For isntance, on Mac one can look in Activity Monitor, find the `pop-node` process and force quit. The network will still be running, but without the collator so Pop Network might not be producing
```suggestion
> For instance, on Mac one can look in Activity Monitor, find the `pop-node` process and force quit. The network will still be running, but without the collator so Pop Network might not be producing blocks.
```

2024-08-23 19:37 UTC, peterwht commented on .github/ISSUE_TEMPLATE/release_tracking.md
> +- [ ] (Advised) Runtime upgrade on a local **fork** of Pop Newtork.
```suggestion
- [ ] (Advised) Runtime upgrade on a local **fork** of Pop Network.
```

2024-08-23 19:37 UTC, peterwht commented on .github/ISSUE_TEMPLATE/release_tracking.md
> +_More instructions around using chopsticks for this can be found in [.chopsticks direcotry](../../.chopsticks)_
```suggestion
_More instructions around using chopsticks for this can be found in [.chopsticks directory](../../.chopsticks)_
```

2024-08-26 14:33 UTC, peterwht approved these changes

2024-08-26 15:39 UTC, Daanvdplas approved these changes

2024-08-26 15:39 UTC, merged