fix(nfts): clippy warnings
r0gue-io/pop-node pull request #391
Opened 2024-11-21 08:19 UTC by chungquantin

Resolve all clippy warnings in the forked pallet-nfts.

2024-11-21 13:03 UTC, Daanvdplas approved these changes
Thank you! I commented for 3 clippy warnings that can be resolved easily as well. Will approve so that we can progress faster

2024-11-21 20:35 UTC, evilrobot-01 requested changes
A few missed warnings, probably missed due to all the missing docs warnings. We enable missing docs warnings so that we get a warning for the code we write, to ensure that we have sufficient docs for publicly available functionality.

As I think it unlikely that we will write the missing docs for the forked pallet, I suggest we silence them on a case by case basis, otherwise we will be faced with more noise on each subsequent review to this pallet. Its quick to sort now and will make reviewing much easier, especially due to the scale of this pallet.

2024-11-22 04:54 UTC, chungquantin commented on pallets/nfts/src/features/metadata.rs
>  			}
Thank you! I did not add it because I don't want to make changes to the code structure of the original pallet. Will be more cautious 🙏

2024-11-22 10:29 UTC, evilrobot-01 approved these changes
Great, tyvm!

2024-11-22 10:29 UTC, merged

2024-11-22 10:34 UTC, evilrobot-01 commented on pallets/nfts/src/features/metadata.rs
>  			}
No problem, but if this was the case there was no way for anyone to know this. A simple comment on the PR at that location wouldve communicated that to others, coming back to giving it a quick review yourself first. Its simply trying to minimise the feedback loop for all concerned.