chore: update codegen
r0gue-io/pop-node pull request #83
Opened 2024-04-25 10:55 UTC by brunopgalvao

You can update the codegen for each respective chain by specifying the url:
```
subxt codegen --url ws://127.0.0.1:65068 | rustfmt > interface.rs
```
And copying the output (`interface.rs`) to its respective file.

2024-04-30 05:36 UTC, Daanvdplas approved these changes

2024-04-30 12:52 UTC, Daanvdplas requested changes
Still get the same error when running zombienet with relay v1.9.0

2024-04-30 14:25 UTC, brunopgalvao commented
> Still get the same error when running zombienet with relay v1.9.0

Most likely you will need to re-run these commands and re-create the metadata:
```
subxt codegen --url ws://127.0.0.1:58043 | rustfmt > rococo_interface.rs
subxt codegen --url ws://127.0.0.1:58051 | rustfmt > pop_interface.rs
```
Then run again.

Anytime the runtime changes, which for us will be quite often because we are building Pop Network, then we will have to recreate the metadata with the above command.

2024-04-30 14:50 UTC, Daanvdplas commented
> > Still get the same error when running zombienet with relay v1.9.0

Also fails with relay v1.8.0 for me

2024-05-02 04:27 UTC, brunopgalvao commented
> Also fails with relay v1.8.0 for me

Are you getting the error: `Error: Metadata(IncompatibleCodegen)`? If so you will need to re-run those commands properly.

Let's hop on a call when you are back and we can look into it.

2024-05-08 07:10 UTC, brunopgalvao commented on Cargo.lock
> +version = "0.22.4"
`jsonrpsee` is getting bumped here. I would not want the dependencies in this script to conflict with the dependencies of the pop-node.

One thought is to create a `Cargo.toml` within this project directory.

2024-05-09 07:04 UTC, Daanvdplas commented
Closed by #87

2024-05-09 07:05 UTC, Daanvdplas approved these changes

2024-05-09 07:10 UTC, evilrobot-01 reviewed
I don't know that we need to bump subxt here. I just updated subxt-cli locally and used it to generate the updated interface, which is probably all it needs.

Suggest reverting the subxt bump in cargo toml and lock and then retesting to see if all still works.

2024-05-09 07:31 UTC, Daanvdplas commented
Will test now

2024-05-09 07:59 UTC, Daanvdplas commented
Getting this error when running the script, 

![Screenshot 2024-05-09 at 09 57 39](https://github.com/r0gue-io/pop-node/assets/93204684/8af35dc9-9a81-44f4-8981-bfb4ef15fe3f)

2024-05-09 09:24 UTC, brunopgalvao commented
I get the same error as Daan if I revert the subxt and subxt-signer to 0.34.0 on this branch and `cargo build`.

2024-05-09 10:17 UTC, brunopgalvao commented
Two ways that I see this being solved:

1. Make this script into its own crate with its own `Cargo.toml` file
2. Create a namespace for `subxt` and `subxt-signer` for this script

2024-05-15 13:06 UTC, brunopgalvao commented
Closing this. Re-open when we have a proper solution in-place for this.

2024-05-15 13:06 UTC, closed without merging